# Sample .travis.yml for R projects.
#
# See https://github.com/craigcitro/r-travis

language: c

env:
  global:
    - R_BUILD_ARGS="--no-build-vignettes --no-manual"
    - R_CHECK_ARGS="--no-build-vignettes --no-manual --as-cran"

script: 
  - ./travis-tool.sh run_tests

before_install:
  - curl -OL http://raw.github.com/craigcitro/r-travis/master/scripts/travis-tool.sh
  - chmod 755 ./travis-tool.sh
  - ./travis-tool.sh bootstrap
  - sudo add-apt-repository -y ppa:edd/misc
  - sudo apt-get update -q

install:
  - ./travis-tool.sh install_aptget r-cran-rcpp r-cran-matrix r-cran-inline r-cran-runit r-cran-pkgkitten
# Note: if Rcpp from Github is needed, use following line and remove Rcpp from previous line
#  - ./travis-tool.sh install_github RcppCore/Rcpp

after_failure:
  - ./travis-tool.sh dump_logs

notifications:
  email:
    on_success: change
    on_failure: change

